export * from './training.type'
export * from './gymTraining.type'
export * from './getUserTrainings.type'
export * from './markVisitingTraining.type'
export * from './getTrainingHistory.type'
export * from './createOneTraining.type'
